import fs from 'node:fs';
const ui=fs.readFileSync('ui/phase14.js','utf8');
const css=fs.readFileSync('ui/phase14.css','utf8');
const loader=fs.readFileSync('ui/avare-nav-guard.js','utf8');
const schema=fs.readFileSync('db/9_8_customer_crm_schema.sql','utf8');
let pass=0,total=0;const check=(label,ok)=>{total++;if(!ok){console.error('FAIL ',label);process.exitCode=1}else{pass++;console.log('PASS ',label)}};
check('phase14 loader',loader.includes("script.src='phase14.js'"));
check('sem innerHTML',!ui.includes('innerHTML'));
check('sem eval',!ui.includes('eval('));
check('sem URL remota',!/(https?:\/\/)/.test(ui));
check('CRM Operacional presente',ui.includes('CRM Operacional'));
check('cadastro rápido presente',ui.includes('Cadastro rápido'));
check('busca por telefone/código',ui.includes('telefone')&&ui.includes('código'));
check('ficha com abas',ui.includes('Resumo')&&ui.includes('Endereços')&&ui.includes('Fidelidade')&&ui.includes('Financeiro'));
check('privacidade por função',ui.includes('Privacidade por função')&&ui.includes('Garçom')&&ui.includes('Suporte'));
check('NEXO Aprender integrado',ui.includes('NEXO Aprender'));
check('duplicidade por telefone no schema',schema.includes('ux_crm_customer_phone'));
check('múltiplos endereços',schema.includes('crm_customer_address'));
check('endereço principal único',schema.includes('ux_crm_primary_address'));
check('fidelidade',schema.includes('crm_customer_loyalty'));
check('financeiro separado',schema.includes('crm_customer_finance'));
check('histórico de pedidos',schema.includes('crm_customer_order_link'));
check('auditoria',schema.includes('crm_customer_audit'));
check('revisão de duplicidade',schema.includes('crm_duplicate_review'));
check('resumo agregado',schema.includes('crm_customer_summary'));
check('responsivo',css.includes('@media(max-width:600px)'));
console.log(`\nResultado Phase 14: ${pass}/${total} verificações PASS`);if(pass!==total)process.exit(1);
