import fs from 'node:fs';
const ui=fs.readFileSync('ui/phase8.js','utf8');
const css=fs.readFileSync('ui/phase8.css','utf8');
const loader=fs.readFileSync('ui/avare-nav-guard.js','utf8');
const schema=fs.readFileSync('db/9_8_product_commercial_schema.sql','utf8');
const seed=fs.readFileSync('db/9_8_product_commercial_seed.sql','utf8');
let pass=0,total=0;
function check(label,ok){total++;if(!ok){console.error('FAIL ',label);process.exitCode=1}else{pass++;console.log('PASS ',label)}}
check('phase8 carregada por bootstrap self',loader.includes("script.src='phase8.js'")&&loader.includes("script.async=false"));
check('phase8 sem innerHTML',!ui.includes('innerHTML'));
check('phase8 sem insertAdjacentHTML',!ui.includes('insertAdjacentHTML'));
check('phase8 sem eval',!ui.includes('eval('));
check('phase8 sem new Function',!ui.includes('new Function'));
check('phase8 sem URL remota',!/(https?:\/\/)/.test(ui));
check('phase8 CSS local/self',ui.includes("l.href='phase8.css'"));
check('Cadastro Comercial 360 presente',ui.includes('Cadastro Comercial 360'));
check('Preço de compra e último custo',ui.includes('Compra ')&&ui.includes('Último '));
check('Varejo e atacado',ui.includes('Varejo ')&&ui.includes('Atacado '));
check('Margem e markup separados',ui.includes('Margem ')&&ui.includes('Markup '));
check('lucro em R$ calculado',ui.includes('Lucro ')&&ui.includes('p.retail-p.cost'));
check('estoque usa disponível físico-reservado',ui.includes('p.stock-p.reserved'));
check('estoque baixo usa disponível <= mínimo',ui.includes('available(p)<=p.min'));
check('validade por lote/FEFO explicada',ui.includes('FEFO')&&schema.includes('product_inventory_lot'));
check('entrada de compra transacional',ui.includes('uma única transação')&&schema.includes("'PURCHASE_IN'"));
check('código de barras USB-HID',ui.includes('USB-HID'));
check('código de barras câmera PWA',ui.includes('Câmera')&&ui.includes('Garçom/PWA'));
check('código de barras manual fallback',ui.includes('Manual')&&ui.includes('Fallback obrigatório'));
check('relatório mais vendidos',ui.includes('Mais vendidos'));
check('relatório estoque baixo',ui.includes('Estoque baixo'));
check('relatório lucro e margem',ui.includes('Lucro e margem'));
check('relatório compras',ui.includes("['Compras'"));
check('relatório movimentações',ui.includes("['Movimentações'"));
check('relatório validade',ui.includes("['Validade'"));
for(const cat of ['Marmitas','Potes','Copos','Tampas','Sacolas','Caixas','Talheres','Guardanapos','Filmes','Bobinas','Embalagens para Delivery'])check(`categoria ${cat}`,seed.includes(`'${cat}'`));
for(const table of ['product_category_core','product_master_core','product_supplier_link','product_cost_state','product_price_state','product_stock_policy','product_stock_balance','product_inventory_lot','product_inventory_movement','purchase_receipt_core','purchase_receipt_item_core','product_barcode_scan_event'])check(`schema cria ${table}`,schema.includes(`CREATE TABLE IF NOT EXISTS ${table}`));
check('view de rentabilidade presente',schema.includes('CREATE VIEW IF NOT EXISTS product_profitability_view'));
check('layout phase8 responsivo',css.includes('@media(max-width:640px)'));
console.log(`\nResultado Phase 8: ${pass}/${total} verificações PASS`);
if(pass!==total)process.exit(1);
