import fs from 'node:fs';
const ui=fs.readFileSync('ui/phase13.js','utf8');
const css=fs.readFileSync('ui/phase13.css','utf8');
const loader=fs.readFileSync('ui/avare-nav-guard.js','utf8');
const schema=fs.readFileSync('db/9_8_delivery_enterprise_extension.sql','utf8');
let pass=0,total=0;const check=(n,ok)=>{total++;if(ok){pass++;console.log('PASS ',n)}else{console.error('FAIL ',n);process.exitCode=1}};
check('phase13 carregada por bootstrap self',loader.includes("script.src='phase13.js'")&&loader.includes('phase13Loader'));
check('phase13 CSS local/self',ui.includes("l.href='phase13.css'"));
check('phase13 sem innerHTML',!ui.includes('innerHTML'));
check('phase13 sem eval/new Function',!ui.includes('eval(')&&!ui.includes('new Function'));
check('phase13 sem URL remota',!/(https?:\/\/)/.test(ui));
check('central continua dentro de Delivery',ui.includes("getElementById('page-delivery')")&&ui.includes('NEXO Delivery — Centro de Operações'));
check('mapa é demonstrativo e não rastreia de verdade',ui.includes('Mapa demonstrativo • sem rastreamento real'));
check('layout possui lista mapa e detalhes',ui.includes('p13-active')&&ui.includes('p13-map')&&ui.includes('p13-detail'));
check('indicadores principais presentes',ui.includes('Entregas hoje')&&ui.includes('Em rota')&&ui.includes('Atrasadas')&&ui.includes('Faturamento'));
check('rota externa permanece privada',ui.includes('deep link pertence à camada mobile privada'));
check('finalização exige servidor',ui.includes('servidor privado deve validar permissão, estado e idempotência'));
check('rastreamento temporário documentado',ui.includes('Rastreamento temporário')&&ui.includes('Encerra ao concluir a entrega.'));
check('schema cria sessão de rastreamento',schema.includes('CREATE TABLE IF NOT EXISTS delivery_tracking_session'));
check('schema impede duas sessões ativas por pedido',schema.includes('uq_delivery_tracking_active_order'));
check('schema valida latitude/longitude',schema.includes('latitude BETWEEN -90 AND 90')&&schema.includes('longitude BETWEEN -180 AND 180'));
check('schema cria snapshot de rota',schema.includes('delivery_route_snapshot'));
check('schema cria eventos de atraso',schema.includes('delivery_delay_event'));
check('schema cria métricas diárias',schema.includes('delivery_daily_metric'));
check('retenção de localização prevista',schema.includes('retention_until'));
check('layout Delivery responsivo',css.includes('@media(max-width:760px)')&&css.includes('@media(max-width:1180px)'));
console.log(`\nResultado Phase 13 Delivery Enterprise: ${pass}/${total} verificações PASS`);if(pass!==total)process.exit(1);
