import fs from 'node:fs';
const ui=fs.readFileSync('ui/phase11.js','utf8');
const css=fs.readFileSync('ui/phase11.css','utf8');
const loader=fs.readFileSync('ui/avare-nav-guard.js','utf8');
const schema=fs.readFileSync('db/9_8_fiscal_lab_schema.sql','utf8');
let pass=0,total=0;const check=(n,ok)=>{total++;if(ok){pass++;console.log('PASS ',n)}else{console.error('FAIL ',n);process.exitCode=1}};
check('phase11 carregada por bootstrap self',loader.includes("script.src='phase11.js'")&&loader.includes('phase11Loader'));
check('phase11 CSS local/self',ui.includes("l.href='phase11.css'"));
check('phase11 sem innerHTML',!ui.includes('innerHTML'));
check('phase11 sem eval/new Function',!ui.includes('eval(')&&!ui.includes('new Function'));
check('phase11 sem URL remota',!/(https?:\/\/)/.test(ui));
check('Fiscal permanece subárea sem novo menu top-level',ui.includes("getElementById('page-integracoes')"));
check('módulo fiscal desativado por padrão',ui.includes('DESATIVADO POR PADRÃO'));
check('wizard possui seis etapas',ui.includes('Dados da Empresa')&&ui.includes('Teste e Finalização')&&ui.includes('Etapa ${wizardStep}/6'));
check('produção bloqueada no LAB',ui.includes('Produção bloqueada no LAB'));
check('IA não decide tributação',ui.includes('A IA não escolhe imposto'));
check('produtos possuem pendências fiscais',ui.includes('NCM 8 dígitos')&&ui.includes('CST/CSOSN'));
check('schema possui perfil de empresa',schema.includes('CREATE TABLE IF NOT EXISTS fiscal_company_profile'));
check('schema possui regras versionadas',schema.includes('CREATE TABLE IF NOT EXISTS fiscal_rule_version'));
check('schema possui documento fiscal idempotente',schema.includes('idempotency_key TEXT NOT NULL UNIQUE'));
check('schema não armazena segredo do certificado',schema.includes('secret_material_present INTEGER NOT NULL DEFAULT 0 CHECK(secret_material_present=0)'));
check('schema possui auditoria',schema.includes('CREATE TABLE IF NOT EXISTS fiscal_audit'));
check('schema possui tentativas de transmissão',schema.includes('CREATE TABLE IF NOT EXISTS fiscal_transmission_attempt'));
check('regra SINIEF 11/25 está histórica/revogada',schema.includes("'NFCE_RECIPIENT_CNPJ_POLICY'")&&schema.includes("'REVOKED'")&&schema.includes('"enforce":false'));
check('motor exige fonte e vigência',schema.includes('source_authority TEXT NOT NULL')&&schema.includes('source_reference TEXT NOT NULL')&&schema.includes('valid_from TEXT'));
check('layout fiscal responsivo',css.includes('@media(max-width:760px)'));
console.log(`\nResultado Phase 11 Fiscal: ${pass}/${total} verificações PASS`);if(pass!==total)process.exit(1);
