import fs from 'node:fs';
const ui=fs.readFileSync('ui/phase15.js','utf8');
const css=fs.readFileSync('ui/phase15.css','utf8');
const loader=fs.readFileSync('ui/avare-nav-guard.js','utf8');
const schema=fs.readFileSync('db/9_8_weighing_selfservice_schema.sql','utf8');
let pass=0,total=0;const check=(label,ok)=>{total++;if(!ok){console.error('FAIL ',label);process.exitCode=1}else{pass++;console.log('PASS ',label)}};
check('phase15 loader',loader.includes("script.src='phase15.js'"));
check('sem innerHTML',!ui.includes('innerHTML'));
check('sem eval',!ui.includes('eval('));
check('sem URL remota',!/(https?:\/\/)/.test(ui));
check('Pesagem & Self-Service presente',ui.includes('Pesagem & Self-Service'));
check('peso bruto/tara/liquido',ui.includes('Peso bruto')&&ui.includes('Tara')&&ui.includes('Peso líquido'));
check('cálculo total central demonstrado',ui.includes('priceKg')&&ui.includes('Math.round'));
check('integração de balança desacoplada',ui.includes('Camada desacoplada'));
check('sem alegação de hardware real',ui.includes('Sem hardware real'));
check('rendimento e perdas',ui.includes('Rendimento & Perdas'));
check('estoque fracionado',ui.includes('Estoque fracionado'));
check('tipos de venda no schema',schema.includes("'UNIT','WEIGHT','VOLUME','SELF_SERVICE_KG','SELF_SERVICE_FIXED','COMBO'"));
check('tara validada no schema',schema.includes('tare_grams<=gross_grams'));
check('peso líquido consistente',schema.includes('net_grams=gross_grams-tare_grams'));
check('idempotência de pesagem',schema.includes('idempotency_key TEXT NOT NULL UNIQUE'));
check('regra de barcode configurável',schema.includes('weighing_barcode_rule'));
check('movimento de estoque',schema.includes('weighing_inventory_movement'));
check('produção/rendimento',schema.includes('weighing_production_batch'));
check('inventário auditável',schema.includes('weighing_inventory_count'));
check('fila de etiqueta',schema.includes('weighing_label_job'));
check('auditoria',schema.includes('weighing_audit'));
check('responsivo',css.includes('@media(max-width:600px)'));
console.log(`\nResultado Phase 15: ${pass}/${total} verificações PASS`);if(pass!==total)process.exit(1);
