import fs from 'node:fs';
const ui=fs.readFileSync('ui/phase12.js','utf8');
const css=fs.readFileSync('ui/phase12.css','utf8');
const loader=fs.readFileSync('ui/avare-nav-guard.js','utf8');
const schema=fs.readFileSync('db/9_8_aprender_schema.sql','utf8');
let pass=0,total=0;const check=(n,ok)=>{total++;if(ok){pass++;console.log('PASS ',n)}else{console.error('FAIL ',n);process.exitCode=1}};
check('phase12 carregada por bootstrap self',loader.includes("script.src='phase12.js'")&&loader.includes('phase12Loader'));
check('phase12 CSS local/self',ui.includes("l.href='phase12.css'"));
check('phase12 sem innerHTML',!ui.includes('innerHTML'));
check('phase12 sem eval/new Function',!ui.includes('eval(')&&!ui.includes('new Function'));
check('NEXO Aprender integrado ao Suporte',ui.includes("getElementById('page-suporte')")&&ui.includes('NEXO Aprender'));
check('quatro níveis de aprendizado presentes',ui.includes('ENTENDER → EXECUTAR → CORRIGIR → APERFEIÇOAR'));
check('implantação guiada contém Fiscal e Backup',ui.includes("['Backup',1]")&&ui.includes("['Fiscal',0]"));
check('treinamento por função inclui cinco perfis',ui.includes('ADMIN')&&ui.includes('CAIXA')&&ui.includes('GARCOM')&&ui.includes('COZINHA')&&ui.includes('ENTREGADOR'));
check('modo guiado possui passos',ui.includes('PASSO ${idx+1} DE ${steps.length}')&&ui.includes('Clique em Produtos.'));
check('ajuda é versionada',ui.includes('filtrada pela versão instalada'));
check('schema cria trilhas',schema.includes('CREATE TABLE IF NOT EXISTS learning_path'));
check('schema cria aulas e passos',schema.includes('learning_lesson')&&schema.includes('learning_step'));
check('schema cria progresso',schema.includes('learning_progress'));
check('schema cria eventos minimizados',schema.includes('learning_event'));
check('schema cria base de conhecimento versionada',schema.includes('knowledge_article')&&schema.includes('knowledge_version'));
check('governança de conteúdo explícita',schema.includes("'DRAFT','REVIEW','APPROVED','PUBLISHED','ARCHIVED'"));
check('handoff para suporte presente',schema.includes('learning_support_handoff'));
check('contexto IA evita conteúdo operacional completo',schema.includes('learning_ai_interaction')&&!schema.includes('customer_phone'));
check('conteúdo possui faixa de versão',schema.includes('software_version_min')&&schema.includes('software_version_max'));
check('layout Aprender responsivo',css.includes('@media(max-width:760px)'));
console.log(`\nResultado Phase 12 Aprender: ${pass}/${total} verificações PASS`);if(pass!==total)process.exit(1);
