(()=>{
'use strict';
const d=document;
const n=(tag,cls,text)=>{const el=d.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el};
const pill=(text,tone='neutral')=>n('span',`pill ${tone}`,text);
const head=(title,sub,side)=>{const h=n('div','panel-head');const t=n('div');t.append(n('h2','',title),n('p','',sub));h.append(t);if(side)h.append(side);return h};
const announce=msg=>{const live=d.getElementById('liveRegion');if(live)live.textContent=msg};
const customers=[
 {id:'C001',name:'João da Silva',phone:'(14) 9XXXX-0101',status:'Ativo',orders:84,total:482000,last:'03/09/2026',channel:'Delivery',addresses:3,tier:'OURO',points:840,open:12000,limit:50000},
 {id:'C002',name:'Maria Oliveira',phone:'(14) 9XXXX-0202',status:'Ativo',orders:31,total:176500,last:'02/09/2026',channel:'Mesa',addresses:1,tier:'PRATA',points:420,open:0,limit:30000},
 {id:'C003',name:'Carlos Souza',phone:'(14) 9XXXX-0303',status:'Inativo',orders:12,total:59000,last:'18/07/2026',channel:'Balcão',addresses:2,tier:'STANDARD',points:90,open:0,limit:0}
];
function money(cents){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100)}
function ensureCss(){if(d.querySelector('link[data-phase14-css]'))return;const l=n('link');l.rel='stylesheet';l.href='phase14.css';l.dataset.phase14Css='true';d.head.append(l)}
function metric(label,value,detail,tone){const a=n('article',`module-metric ${tone}`);a.append(n('span','module-metric-label',label),n('strong','module-metric-value',value),n('small','module-metric-detail',detail));return a}
function render(){const page=d.getElementById('page-clientes');if(!page||d.getElementById('p14CRM'))return;const root=n('section','p14-root');root.id='p14CRM';
 const hero=n('article','panel p14-hero');hero.append(head('NEXO Clientes — CRM Operacional','Cadastro rápido no atendimento e ficha completa na gestão',pill('Fase 14 LAB','purple')));const actions=n('div','p14-actions');const quick=n('button','primary p14-action','+ Cadastro rápido');quick.type='button';quick.dataset.p14Action='quick';const full=n('button','ghost p14-action','Abrir ficha completa');full.type='button';full.dataset.p14Action='full';actions.append(quick,full);hero.append(actions);root.append(hero);
 const metrics=n('div','module-metrics');metrics.append(metric('Clientes ativos','2','Dados DEMO','green'),metric('Frequentes','1','84 pedidos','blue'),metric('Inativos','1','Mais de 30 dias','amber'),metric('Fidelidade','840 pts','Maior saldo DEMO','purple'));root.append(metrics);
 const grid=n('div','module-grid two');
 const search=n('article','panel');search.append(head('Busca inteligente','Nome, telefone, CPF/CNPJ quando necessário ou código',pill('Anti-duplicidade','ok')));const input=n('input','p14-search');input.type='search';input.placeholder='Digite nome, telefone ou código';input.autocomplete='off';input.dataset.p14Search='true';search.append(input);const results=n('div','p14-results');results.id='p14Results';search.append(results);grid.append(search);
 const privacy=n('article','panel');privacy.append(head('Privacidade por função','Menor privilégio e minimização de dados',pill('LGPD','blue-pill')));const roles=n('div','p14-role-list');[['Garçom','Nome, telefone e endereço necessário ao atendimento'],['Caixa','Identificação e dados necessários à venda'],['Administrador','Ficha completa e gestão'],['Financeiro','Limite, aberto e vencido quando autorizado'],['Suporte','Somente contexto técnico necessário']].forEach(([r,s])=>{const row=n('div','p14-role');row.append(n('strong','',r),n('span','',s));roles.append(row)});privacy.append(roles);grid.append(privacy);root.append(grid);
 const detail=n('article','panel p14-detail');detail.id='p14Detail';detail.append(head('Ficha do cliente','Resumo • Dados • Endereços • Pedidos • Fidelidade • Financeiro • Observações',pill('Registro central','green')));root.append(detail);
 const learn=n('article','panel');learn.append(head('NEXO Aprender','Ajuda contextual para cadastro e atendimento',pill('Como fazer?','purple')));const steps=n('ol','p14-learn');['Informe telefone','Informe nome','Complete endereço agora ou depois','Salve e continue o atendimento'].forEach(x=>steps.append(n('li','',x)));learn.append(steps);root.append(learn);
 page.append(root);fillResults(customers);showCustomer(customers[0]);}
function fillResults(list){const box=d.getElementById('p14Results');if(!box)return;box.replaceChildren();if(!list.length){box.append(n('p','p14-empty','Nenhum cliente encontrado.'));return}list.forEach(c=>{const b=n('button','p14-result');b.type='button';b.dataset.p14Customer=c.id;b.append(n('strong','',c.name),n('span','',`${c.phone} • ${c.addresses} endereço(s)`),pill(c.status,c.status==='Ativo'?'ok':'warn'));box.append(b)})}
function showCustomer(c){const box=d.getElementById('p14Detail');if(!box)return;while(box.children.length>1)box.lastChild.remove();const summary=n('div','p14-summary');const title=n('div');title.append(n('h3','',c.name),pill(c.status,c.status==='Ativo'?'ok':'warn'));summary.append(title);const stats=n('div','p14-stats');stats.append(metric('Pedidos',String(c.orders),`Último: ${c.last}`,'blue'),metric('Compras',money(c.total),`Ticket médio: ${money(Math.round(c.total/c.orders))}`,'green'),metric('Preferência',c.channel,`${c.addresses} endereço(s)`,'purple'),metric('Fidelidade',`${c.points} pts`,c.tier,'amber'));summary.append(stats);const tabs=n('div','p14-tabs');['Resumo','Dados','Endereços','Pedidos','Fidelidade','Financeiro','Observações'].forEach((x,i)=>tabs.append(pill(x,i===0?'blue-pill':'neutral')));summary.append(tabs);const finance=n('div','p14-finance');finance.append(n('strong','','Financeiro autorizado'),n('span','',`Limite ${money(c.limit)} • Em aberto ${money(c.open)} • Disponível ${money(Math.max(0,c.limit-c.open))}`));summary.append(finance);box.append(summary)}
function openQuick(){const phone=prompt('Telefone do cliente (LAB):','');if(phone===null)return;const normalized=phone.replace(/\D/g,'');if(!normalized){announce('Informe um telefone para o cadastro rápido.');return}announce('Cadastro rápido preparado no LAB. O backend privado deverá verificar duplicidade antes de salvar.');}
function load(){ensureCss();render()}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',load,{once:true});else load();
d.addEventListener('input',e=>{if(!e.target.matches('[data-p14-search]'))return;const q=e.target.value.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');const list=customers.filter(c=>`${c.id} ${c.name} ${c.phone}`.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(q));fillResults(list)});
d.addEventListener('click',e=>{const c=e.target.closest('[data-p14-customer]');if(c){const item=customers.find(x=>x.id===c.dataset.p14Customer);if(item)showCustomer(item);return}const a=e.target.closest('[data-p14-action]');if(!a)return;if(a.dataset.p14Action==='quick')openQuick();if(a.dataset.p14Action==='full')announce('Ficha completa disponível no painel de Clientes do LAB.');});
})();
