(()=>{
'use strict';
const d=document;
const n=(tag,cls,text)=>{const el=d.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el};
const pill=(text,t='neutral')=>n('span',`pill ${t}`,text);
const head=(title,sub,side)=>{const h=n('div','panel-head');const t=n('div');t.append(n('h2','',title),n('p','',sub));h.append(t);if(side)h.append(side);return h};
const btn=(text,action)=>{const b=n('button','ghost p13-action',text);b.type='button';b.dataset.p13Action=action;return b};
const announce=msg=>{const live=d.getElementById('liveRegion');if(live)live.textContent=msg};
function ensureCss(){if(d.querySelector('link[data-phase13-css]'))return;const l=d.createElement('link');l.rel='stylesheet';l.href='phase13.css';l.dataset.phase13Css='true';d.head.append(l)}
const deliveries=[
 {id:'#0152',client:'João Silva',district:'Centro',driver:'Carlos',status:'EM ROTA',tone:'green',elapsed:'11 min',value:'R$ 52,00',pay:'PIX',eta:'12:47',distance:'3,4 km'},
 {id:'#0153',client:'Maria Souza',district:'Jardim',driver:'—',status:'COZINHA',tone:'warn',elapsed:'18 min',value:'R$ 38,00',pay:'Dinheiro',eta:'—',distance:'—'},
 {id:'#0154',client:'Pedro Lima',district:'Vila Nova',driver:'João',status:'AGUARDANDO',tone:'blue-pill',elapsed:'06 min',value:'R$ 64,00',pay:'Crédito',eta:'13:05',distance:'5,1 km'}
];
function build(){const page=d.getElementById('page-delivery');if(!page||d.getElementById('p13DeliveryEnterprise'))return;const root=n('section','p13-root');root.id='p13DeliveryEnterprise';
 const metrics=n('div','module-metrics');[['Entregas hoje','18','Total','blue'],['Em rota','05','Ativas','green'],['Aguardando','02','Entregador','amber'],['Atrasadas','01','Atenção','red'],['Faturamento','R$ 2.840','Delivery','purple']].forEach(([a,b,c,t])=>{const m=n('article',`module-metric ${t}`);m.append(n('span','module-metric-label',a),n('strong','module-metric-value',b),n('small','module-metric-detail',c));metrics.append(m)});root.append(metrics);
 const shell=n('article','panel p13-shell');shell.append(head('NEXO Delivery — Centro de Operações','Pedido → Produção → Expedição → Rota → Entrega → Pagamento',pill('Mapa demonstrativo • sem rastreamento real','warn')));
 const layout=n('div','p13-layout');const active=n('div','p13-active');active.append(n('h3','', 'Pedidos ativos'));deliveries.forEach((x,i)=>{const row=n('button',`p13-delivery ${i===0?'selected':''}`);row.type='button';row.dataset.p13Action='select';row.dataset.index=String(i);row.append(pill(x.id,'neutral'),n('strong','',x.client),n('span','',`${x.district} • ${x.elapsed}`),pill(x.status,x.tone));active.append(row)});
 const map=n('div','p13-map');map.setAttribute('role','img');map.setAttribute('aria-label','Mapa demonstrativo de rota, sem dados reais');map.append(n('div','p13-origin','📍 Origem'),n('div','p13-route',''),n('div','p13-driver','🛵'),n('div','p13-destination','📍 Destino'));const routeBar=n('div','p13-route-bar');routeBar.id='p13RouteBar';routeBar.append(n('strong','',deliveries[0].distance),n('span','',`ETA ${deliveries[0].eta}`));map.append(routeBar);
 const detail=n('div','p13-detail');detail.id='p13Detail';layout.append(active,map,detail);shell.append(layout);root.append(shell);
 const privacy=n('article','panel');privacy.append(head('Rastreamento temporário','Localização somente durante entrega ativa e conforme política da empresa',pill('Privacidade por padrão','green')));const rules=n('div','p13-rules');['Inicia somente após entrega atribuída/aceita.','Encerra ao concluir a entrega.','Retenção de localização é configurável e limitada.','IA pode detectar atraso, mas não muda status sozinha.','Falha de localização mantém a última posição conhecida e não perde o pedido.'].forEach(x=>{const r=n('div','p13-rule');r.append(pill('✓','ok'),n('span','',x));rules.append(r)});privacy.append(rules);root.append(privacy);page.append(root);renderDetail(0)}
function renderDetail(i){const x=deliveries[i]||deliveries[0];const root=d.getElementById('p13Detail');if(!root)return;root.replaceChildren();root.append(pill(x.status,x.tone),n('h3','',`Entrega ${x.id}`),n('strong','',x.client));[['Bairro',x.district],['Entregador',x.driver],['Pagamento',x.pay],['Valor',x.value],['Distância',x.distance],['ETA',x.eta]].forEach(([a,b])=>{const r=n('div','p13-kv');r.append(n('span','',a),n('strong','',b));root.append(r)});root.append(btn('ABRIR ROTA','route'),btn('DETALHES DO PEDIDO','details'),btn('FINALIZAR ENTREGA','finish'));const bar=d.getElementById('p13RouteBar');if(bar){bar.replaceChildren(n('strong','',x.distance),n('span','',`ETA ${x.eta}`))}}
function load(){ensureCss();build()}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',load,{once:true});else load();
d.addEventListener('click',e=>{const t=e.target.closest('[data-p13-action]');if(!t)return;const a=t.dataset.p13Action;if(a==='select'){d.querySelectorAll('.p13-delivery').forEach(x=>x.classList.remove('selected'));t.classList.add('selected');renderDetail(Number(t.dataset.index||0));announce('Detalhes da entrega atualizados.')}else if(a==='route'){announce('LAB: rota não foi aberta externamente. O deep link pertence à camada mobile privada.')}else if(a==='finish'){announce('LAB: entrega não foi finalizada. O servidor privado deve validar permissão, estado e idempotência.')}else if(a==='details'){announce('LAB: detalhes demonstrativos; nenhum dado pessoal real foi carregado.')}});
})();
