(()=>{
'use strict';
const d=document;
const n=(tag,cls,text)=>{const el=d.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el};
const pill=(text,tone='neutral')=>n('span',`pill ${tone}`,text);
const announce=msg=>{const live=d.getElementById('liveRegion');if(live)live.textContent=msg};
const btn=(text,action,value)=>{const b=n('button','ghost p11-action',text);b.type='button';b.dataset.p11Action=action;if(value!==undefined)b.dataset.value=value;return b};
const head=(title,sub,side)=>{const h=n('div','panel-head');const t=n('div');t.append(n('h2','',title),n('p','',sub));h.append(t);if(side)h.append(side);return h};
let wizardStep=1;
const fiscal={status:'CONFIGURANDO',environment:'HOMOLOGAÇÃO',certificate:'NÃO CONFIGURADO',pendingProducts:4,types:['NF-e 55','NFC-e 65'],rules:'VERSIONADAS'};
function ensureCss(){if(d.querySelector('link[data-phase11-css]'))return;const l=d.createElement('link');l.rel='stylesheet';l.href='phase11.css';l.dataset.phase11Css='true';d.head.append(l)}
function appendFiscal(){const page=d.getElementById('page-integracoes');if(!page||d.getElementById('p11Fiscal'))return;const root=n('section','p11-root');root.id='p11Fiscal';
 const hero=n('article','panel p11-hero');hero.append(head('NEXO Fiscal','Módulo opcional — configuração, homologação e produção controladas',pill('LAB • sem emissão real','warn')));
 const warning=n('div','p11-warning');warning.setAttribute('role','status');warning.append(pill('REGRA DINÂMICA','blue-pill'),n('span','', 'Regras fiscais são versionadas por vigência, UF e fonte oficial. A IA não escolhe imposto, CFOP, CST/CSOSN nem decide se uma regra legal está vigente.'));hero.append(warning);root.append(hero);
 const metrics=n('div','module-metrics');[['Situação',fiscal.status,'Assistente incompleto','amber'],['Ambiente',fiscal.environment,'Produção bloqueada no LAB','blue'],['Certificado',fiscal.certificate,'A1/A3 somente no Core privado','red'],['Pendências',String(fiscal.pendingProducts),'Produtos sem dados fiscais','purple']].forEach(([a,b,c,t])=>{const m=n('article',`module-metric ${t}`);m.append(n('span','module-metric-label',a),n('strong','module-metric-value',b),n('small','module-metric-detail',c));metrics.append(m)});root.append(metrics);
 const grid=n('div','module-grid two');
 const status=n('article','panel');status.append(head('Status Fiscal da Empresa','Visão operacional sem expor certificado ou senha',pill('DESATIVADO POR PADRÃO','neutral')));const list=n('div','p11-list');[['Documentos','NF-e / NFC-e / NFS-e','blue-pill'],['Credenciamento','A confirmar por UF/município','warn'],['Produtos fiscais','NCM • CFOP • CST/CSOSN • origem • unidade','warn'],['Auditoria','Emissão, eventos, rejeições e correlação','ok'],['Backup','Banco + artefatos fiscais no contrato privado','ok']].forEach(([a,b,t])=>{const r=n('div','p11-row');r.append(n('strong','',a),n('span','',b),pill('Definido',t));list.append(r)});status.append(list);
 const wizard=n('article','panel');wizard.id='p11Wizard';wizard.append(head('Assistente Fiscal','O usuário não avança sem completar validações',pill(`Etapa ${wizardStep}/6`,'purple')));const steps=['Dados da Empresa','Opções Fiscais','Certificado Digital','Ambiente e Credenciamento','Produtos Fiscais','Teste e Finalização'];const body=n('div','p11-steps');steps.forEach((s,i)=>{const row=n('div',`p11-step ${i+1===wizardStep?'active':''} ${i+1<wizardStep?'done':''}`);row.append(n('span','p11-step-no',String(i+1)),n('span','',s));body.append(row)});const actions=n('div','p11-actions');actions.append(btn('Voltar','wizard-prev'),btn(wizardStep===6?'Concluir simulação':'Avançar','wizard-next'));wizard.append(body,actions);grid.append(status,wizard);root.append(grid);
 const rules=n('article','panel');rules.append(head('Motor de regras fiscais','Fonte oficial + vigência + jurisdição + snapshot por documento',pill('Determinístico','green')));const note=n('p','p11-note','O LAB registra inclusive regras históricas revogadas sem aplicá-las. Antes de produção, o Agent deverá sincronizar/validar a regra vigente e preservar o snapshot utilizado em cada documento.');rules.append(note);root.append(rules);
 page.append(root);
 const prod=d.getElementById('page-produtos');if(prod&&!d.getElementById('p11ProductFiscal')){const card=n('article','panel p11-product');card.id='p11ProductFiscal';card.append(head('Pendências Fiscais','Campos exigidos somente quando o módulo fiscal estiver habilitado',pill('4 pendências DEMO','warn')));const fields=n('div','p11-tags');['NCM 8 dígitos','CFOP','CST/CSOSN','Origem','Unidade fiscal'].forEach(x=>fields.append(pill(x,'neutral')));card.append(fields,n('p','p11-note','O NEXO orienta, valida formato e aponta inconsistências; a parametrização tributária deve ser confirmada pelo responsável fiscal/contador.'));prod.append(card)}
}
function load(){ensureCss();appendFiscal()}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',load,{once:true});else load();
d.addEventListener('click',e=>{const t=e.target.closest('[data-p11-action]');if(!t)return;if(t.dataset.p11Action==='wizard-prev'){wizardStep=Math.max(1,wizardStep-1)}else if(t.dataset.p11Action==='wizard-next'){if(wizardStep<6)wizardStep++;else{announce('Simulação fiscal concluída no LAB. Nenhuma nota foi emitida.');t.textContent='Simulação concluída';t.disabled=true;return}}const old=d.getElementById('p11Fiscal');old?.remove();appendFiscal();announce(`Assistente Fiscal: etapa ${wizardStep} de 6.`)});
})();
