(()=>{
'use strict';
const d=document;const n=(tag,cls,text)=>{const el=d.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el};
const pill=(text,tone='neutral')=>n('span',`pill ${tone}`,text);const head=(title,sub,side)=>{const h=n('div','panel-head');const t=n('div');t.append(n('h2','',title),n('p','',sub));h.append(t);if(side)h.append(side);return h};
const metric=(a,b,c,t)=>{const x=n('article',`module-metric ${t}`);x.append(n('span','module-metric-label',a),n('strong','module-metric-value',b),n('small','module-metric-detail',c));return x};
const announce=m=>{const live=d.getElementById('liveRegion');if(live)live.textContent=m};
const demo={gross:650,tare:100,priceKg:5990,product:'Self-Service'};
function money(c){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100)}function total(){return Math.round((demo.gross-demo.tare)*demo.priceKg/1000)}
function ensureCss(){if(d.querySelector('link[data-phase15-css]'))return;const l=n('link');l.rel='stylesheet';l.href='phase15.css';l.dataset.phase15Css='true';d.head.append(l)}
function render(){const products=d.getElementById('page-produtos');if(products&&!d.getElementById('p15Weighting')){const root=n('section','p15-root');root.id='p15Weighting';root.append(head('NEXO Pesagem & Self-Service','Produtos por peso, balança, tara, etiqueta e estoque fracionado',pill('Fase 15 LAB','purple')));const metrics=n('div','module-metrics');metrics.append(metric('Pesagens hoje','128','Dados DEMO','blue'),metric('Kg vendidos','84,5 kg','Self-service','green'),metric('Perdas','3,2 kg','Produção DEMO','amber'),metric('Balanças','2 online • 1 offline','Sem hardware real','red'));root.append(metrics);
 const grid=n('div','module-grid two');const sale=n('article','panel p15-sale');sale.append(head('Venda por peso','Peso bruto → tara → peso líquido → total',pill('Cálculo central','ok')));[['Produto',demo.product],['Peso bruto',`${(demo.gross/1000).toFixed(3).replace('.',',')} kg`],['Tara',`${(demo.tare/1000).toFixed(3).replace('.',',')} kg`],['Peso líquido',`${((demo.gross-demo.tare)/1000).toFixed(3).replace('.',',')} kg`],['Preço/kg',money(demo.priceKg)],['Total',money(total())]].forEach(([a,b])=>{const r=n('div','p15-line');r.append(n('span','',a),n('strong','',b));sale.append(r)});const b=n('button','primary');b.type='button';b.dataset.p15Action='confirm';b.textContent='Confirmar pesagem DEMO';sale.append(b);grid.append(sale);
 const setup=n('article','panel');setup.append(head('Integração de balança','Camada desacoplada por conector/protocolo',pill('Sem fabricante fixo','blue-pill')));const list=n('div','p15-list');[['Balança 01','USB/Serial','ONLINE'],['Balança 02','Rede','ONLINE'],['Balança 03','Serial','OFFLINE']].forEach(([a,b,s])=>{const r=n('div','p15-row');r.append(n('strong','',a),n('span','',b),pill(s,s==='ONLINE'?'ok':'danger'));list.append(r)});setup.append(list,n('p','p15-note','Homologação exige teste físico por fabricante/modelo. O LAB não lê porta serial, USB ou rede.'));grid.append(setup);root.append(grid);
 const rules=n('article','panel');rules.append(head('Regras de precisão e etiqueta','Sem misturar unidade/peso e sem ponto flutuante monetário inadequado',pill('Auditável','green')));const tags=n('div','p15-tags');['Unidade','Peso','Volume','Self-Service/kg','Preço fixo','Combo','Tara cadastrada','Tara manual','Tara da balança','Código de balança configurável','FEFO/estoque fracionado'].forEach(x=>tags.append(pill(x,'neutral')));rules.append(tags);root.append(rules);products.append(root)}
 const stock=d.getElementById('page-estoque');if(stock&&!d.getElementById('p15Yield')){const card=n('article','panel p15-yield');card.id='p15Yield';card.append(head('Rendimento & Perdas por Peso','Planejado × real com motivo e auditoria',pill('Estoque fracionado','amber')));card.append(n('p','p15-note','Exemplo DEMO: entrada 10,000 kg → perda 1,200 kg → produção útil 8,800 kg. Ajustes exigem motivo, usuário, data e hora.'));stock.append(card)}
 const integ=d.getElementById('page-integracoes');if(integ&&!d.getElementById('p15Device')){const card=n('article','panel');card.id='p15Device';card.append(head('Balanças e Etiquetas','Conectores homologados ficam na Central de Drivers/Periféricos',pill('Contrato LAB','neutral')));card.append(n('p','p15-note','Fluxo alvo: balança → conector NEXO → pesagem → pedido → estoque → caixa → fiscal → financeiro.'));integ.append(card)}}
function load(){ensureCss();render()}if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',load,{once:true});else load();
d.addEventListener('click',e=>{const t=e.target.closest('[data-p15-action="confirm"]');if(!t)return;t.disabled=true;t.textContent='Pesagem validada no LAB';announce('Pesagem demonstrativa validada. Nenhuma venda, estoque ou caixa real foi alterado.');});
})();
