(()=>{
'use strict';
const d=document;
const el=(tag,cls,text)=>{const n=d.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const pill=(text,tone='neutral')=>el('span',`pill ${tone}`,text);
const button=(text,action,value,cls='ghost')=>{const b=el('button',cls,text);b.type='button';b.dataset.p8Action=action;if(value!==undefined)b.dataset.value=String(value);return b};
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const money=cents=>brl.format((Number(cents)||0)/100);
const products=[
 {sku:'EMB-001',name:'Marmita Alumínio 750 ml',category:'Marmitas',brand:'Genérica',unit:'UN',barcode:'7890000000011',supplier:'Fornecedor de embalagem',cost:85,lastCost:88,retail:150,wholesale:130,stock:86,reserved:10,min:100,expiry:null},
 {sku:'EMB-002',name:'Pote Plástico 500 ml',category:'Potes',brand:'Genérica',unit:'UN',barcode:'7890000000028',supplier:'Fornecedor de embalagem',cost:62,lastCost:65,retail:120,wholesale:100,stock:220,reserved:20,min:100,expiry:null},
 {sku:'EMB-004',name:'Tampa para Pote 500 ml',category:'Tampas',brand:'Genérica',unit:'UN',barcode:'7890000000042',supplier:'Fornecedor de embalagem',cost:28,lastCost:30,retail:60,wholesale:50,stock:94,reserved:4,min:100,expiry:null},
 {sku:'EMB-006',name:'Caixa Delivery 35 cm',category:'Caixas',brand:'Genérica',unit:'UN',barcode:'7890000000066',supplier:'Fornecedor de embalagem',cost:180,lastCost:185,retail:320,wholesale:285,stock:42,reserved:2,min:50,expiry:null},
 {sku:'EMB-010',name:'Bobina Térmica 80 x 40',category:'Bobinas',brand:'Genérica',unit:'CX',barcode:'7890000000103',supplier:'Fornecedor de embalagem',cost:6200,lastCost:6350,retail:7990,wholesale:7490,stock:3,reserved:0,min:2,expiry:null},
 {sku:'BEB-001',name:'Coca-Cola 350 ml',category:'Bebidas',brand:'Coca-Cola',unit:'UN',barcode:'7894900010015',supplier:'Fornecedor de bebidas',cost:320,lastCost:330,retail:650,wholesale:590,stock:50,reserved:6,min:24,expiry:'15/03/2027'},
 {sku:'ING-001',name:'Queijo Muçarela',category:'Ingredientes',brand:'Genérica',unit:'KG',barcode:'—',supplier:'Fornecedor de frios',cost:3250,lastCost:3380,retail:4690,wholesale:null,stock:3.8,reserved:0.5,min:2,expiry:'12/09/2026'}
];
const margin=p=>p.retail>0?(p.retail-p.cost)/p.retail*100:0;
const markup=p=>p.cost>0?(p.retail-p.cost)/p.cost*100:0;
const available=p=>p.stock-p.reserved;
function ensureCss(){if(d.querySelector('link[data-phase8-css]'))return;const l=d.createElement('link');l.rel='stylesheet';l.href='phase8.css';l.dataset.phase8Css='true';d.head.append(l)}
function head(title,subtitle,side){const h=el('div','panel-head');const t=el('div');t.append(el('h2','',title),el('p','',subtitle));h.append(t);if(side)h.append(side);return h}
function metric(label,value,detail,tone='blue'){const m=el('article',`module-metric ${tone}`);m.append(el('span','module-metric-label',label),el('strong','module-metric-value',value),el('small','module-metric-detail',detail));return m}
function renderProductCommercial(){const page=d.getElementById('page-produtos');if(!page||d.getElementById('p8ProductCommercial'))return;const wrap=el('section','p8-wrap');wrap.id='p8ProductCommercial';const metrics=el('div','module-metrics');const avg=products.reduce((s,p)=>s+margin(p),0)/products.length;metrics.append(metric('Itens demonstrados',String(products.length),'Cadastro Comercial 360','blue'),metric('Margem média',`${avg.toFixed(1)}%`,'Margem sobre venda','green'),metric('Estoque baixo',String(products.filter(p=>available(p)<=p.min).length),'Disponível ≤ mínimo','amber'),metric('Com validade',String(products.filter(p=>p.expiry).length),'Controle por lote','purple'));
 const card=el('article','panel');card.append(head('Cadastro Comercial 360','Produto, custo, preço, margem, estoque, validade e fornecedor',pill('Fase 8','blue-pill')));const table=el('div','p8-table');products.forEach(p=>{const r=el('div','p8-product-row');const title=el('div','p8-product-title');title.append(el('strong','',p.name),el('small','',`${p.sku} • ${p.category} • ${p.unit} • ${p.brand}`));const pricing=el('div','p8-pricing');pricing.append(el('span','',`Compra ${money(p.cost)}`),el('span','',`Último ${money(p.lastCost)}`),el('span','',`Varejo ${money(p.retail)}`),el('span','',p.wholesale?`Atacado ${money(p.wholesale)}`:'Atacado —'));const profit=el('div','p8-profit');profit.append(pill(`Lucro ${money(p.retail-p.cost)}`,'ok'),pill(`Margem ${margin(p).toFixed(1)}%`,'blue-pill'),pill(`Markup ${markup(p).toFixed(1)}%`,'purple'));const meta=el('div','p8-meta');meta.append(el('span','',`Estoque ${p.stock} • Disponível ${available(p)}`),pill(available(p)<=p.min?'Estoque baixo':'Estoque OK',available(p)<=p.min?'warn':'ok'),el('span','',`Cód. barras ${p.barcode}`),el('span','',`Fornecedor: ${p.supplier}`),p.expiry?pill(`Validade ${p.expiry}`,'warn'):pill('Sem validade','neutral'));r.append(title,pricing,profit,meta);table.append(r)});card.append(table);wrap.append(metrics,card);page.append(wrap)}
function renderStockExpiry(){const page=d.getElementById('page-estoque');if(!page||d.getElementById('p8StockControl'))return;const panel=el('article','panel p8-stock');panel.id='p8StockControl';panel.append(head('Estoque, Validade e Movimentações','Saldo conciliado por movimentação; lotes com FEFO quando houver vencimento',pill('Rastreável','ok')));const list=el('div','p8-stock-grid');products.filter(p=>available(p)<=p.min||p.expiry).forEach(p=>{const c=el('div','p8-stock-card');c.append(el('strong','',p.name),el('p','',`Físico ${p.stock} • Reservado ${p.reserved} • Disponível ${available(p)} • Mínimo ${p.min}`),p.expiry?pill(`Lote vence ${p.expiry}`,'warn'):pill('Sem controle de validade','neutral'),pill(available(p)<=p.min?'Reposição necessária':'Saldo monitorado',available(p)<=p.min?'danger':'ok'));list.append(c)});panel.append(list);page.append(panel)}
function renderPurchasing(){const page=d.getElementById('page-compras');if(!page||d.getElementById('p8PurchaseFlow'))return;const panel=el('article','panel');panel.id='p8PurchaseFlow';panel.append(head('Entrada de Mercadorias','Recebimento deverá atualizar custo, lote e estoque em uma única transação',pill('Contrato privado','neutral')));const steps=el('div','p8-flow');['Ler código de barras ou buscar produto','Conferir fornecedor, quantidade, custo e validade','Registrar lote quando houver vencimento','Atualizar último custo e custo médio','Gerar movimento PURCHASE_IN','Só confirmar saldo após a transação concluir'].forEach((x,i)=>{const row=el('div','p8-flow-step');row.append(pill(String(i+1),'blue-pill'),el('span','',x));steps.append(row)});panel.append(steps);page.append(panel)}
function renderReports(){const page=d.getElementById('page-relatorios');if(!page||d.getElementById('p8Reports'))return;const panel=el('article','panel');panel.id='p8Reports';panel.append(head('Relatórios de Produtos & Rentabilidade','Visões comerciais propostas para a integração privada',pill('6 relatórios','purple')));const grid=el('div','p8-report-grid');[['Mais vendidos','Quantidade, faturamento, ticket e ranking.'],['Estoque baixo','Atual, disponível, mínimo e sugestão de compra.'],['Lucro e margem','Lucro R$, margem sobre venda e markup sobre custo.'],['Compras','Fornecedor, custo, último custo e evolução.'],['Movimentações','Entradas, saídas, perdas, ajustes e devoluções.'],['Validade','Lotes a vencer, vencidos e consumo FEFO.']].forEach(([a,b])=>{const c=el('div','p8-report-card');c.append(el('strong','',a),el('p','',b));grid.append(c)});panel.append(grid);page.append(panel)}
function renderBarcode(){const page=d.getElementById('page-produtos');if(!page||d.getElementById('p8Barcode'))return;const panel=el('article','panel p8-barcode');panel.id='p8Barcode';panel.append(head('Código de Barras','Leitor USB-HID, câmera do Garçom/PWA quando suportada e entrada manual',pill('3 modos','blue-pill')));const modes=el('div','p8-report-grid');[['USB-HID','Leitor atua como teclado no Windows; normalmente não exige integração especial.'],['Câmera','Garçom/PWA pode ler EAN/Code 128/QR quando o navegador e a câmera permitirem.'],['Manual','Fallback obrigatório para código danificado, dispositivo sem câmera ou falha de permissão.']].forEach(([a,b])=>{const c=el('div','p8-report-card');c.append(el('strong','',a),el('p','',b));modes.append(c)});panel.append(modes,button('Simular leitura LAB','scan','7894900010015','ghost'));const out=el('div','p8-scan-result','Nenhuma leitura simulada.');out.id='p8ScanResult';panel.append(out);page.append(panel)}
function ensureAll(){ensureCss();renderProductCommercial();renderBarcode();renderStockExpiry();renderPurchasing();renderReports()}
d.addEventListener('click',ev=>{const b=ev.target.closest('[data-p8-action]');if(!b)return;if(b.dataset.p8Action==='scan'){const p=products.find(x=>x.barcode===b.dataset.value);const out=d.getElementById('p8ScanResult');if(out)out.textContent=p?`Leitura reconhecida: ${p.name} • ${p.sku}`:'Código não localizado no catálogo LAB.'}});
const observer=new MutationObserver(()=>queueMicrotask(ensureAll));
d.addEventListener('DOMContentLoaded',()=>{ensureAll();observer.observe(d.getElementById('workspace')||d.body,{childList:true,subtree:true})});
})();
