(()=>{
'use strict';
const d=document;
const n=(tag,cls,text)=>{const el=d.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el};
const pill=(text,t='neutral')=>n('span',`pill ${t}`,text);
const head=(title,sub,side)=>{const h=n('div','panel-head');const t=n('div');t.append(n('h2','',title),n('p','',sub));h.append(t);if(side)h.append(side);return h};
const btn=(text,action,value)=>{const b=n('button','ghost p12-action',text);b.type='button';b.dataset.p12Action=action;if(value!==undefined)b.dataset.value=value;return b};
const announce=msg=>{const live=d.getElementById('liveRegion');if(live)live.textContent=msg};
const state={level:'INICIANTE',role:'ADMIN',guideStep:0};
const tracks={ADMIN:['Empresa e usuários','Produtos e estoque','Caixa e financeiro','Delivery','Backup','Fiscal'],CAIXA:['Abertura','Venda','Pagamento','Sangria','Suprimento','Fechamento'],GARCOM:['Mesas','Comandas','Pedidos','Alterações','Observações','Solicitar fechamento'],COZINHA:['Fila','Produção','Prioridade','Pronto'],ENTREGADOR:['Minhas entregas','Endereço e rota','Iniciar','Cheguei','Entregue','Ocorrência']};
function ensureCss(){if(d.querySelector('link[data-phase12-css]'))return;const l=d.createElement('link');l.rel='stylesheet';l.href='phase12.css';l.dataset.phase12Css='true';d.head.append(l)}
function buildLearning(){const page=d.getElementById('page-suporte');if(!page||d.getElementById('p12Aprender'))return;const root=n('section','p12-root');root.id='p12Aprender';
 const hero=n('article','panel');hero.append(head('NEXO Aprender','Ajuda contextual, treinamento guiado e conhecimento versionado',pill('ENTENDER → EXECUTAR → CORRIGIR → APERFEIÇOAR','purple')));hero.append(n('p','p12-note','O sistema ensina no momento em que o usuário precisa. Conteúdo oficial produzido ou sugerido pela IA passa por Rascunho → Revisão → Aprovado → Publicado.'));root.append(hero);
 const setup=n('article','panel');setup.append(head('Comece Aqui','Implantação orientada do primeiro acesso',pill('50% DEMO','blue-pill')));const checklist=n('div','p12-checklist');[['Empresa',1],['Usuário administrador',1],['Produtos',1],['Estoque',0],['Cardápio',0],['Caixa',1],['Delivery',0],['Impressoras',0],['Backup',1],['Fiscal',0]].forEach(([label,ok])=>{const row=n('div','p12-check-row');row.append(pill(ok?'✓':'○',ok?'ok':'neutral'),n('span','',label));checklist.append(row)});setup.append(checklist);root.append(setup);
 const grid=n('div','module-grid two');const profile=n('article','panel');profile.append(head('Treinamento por função','Cada perfil vê somente o que precisa aprender',pill(state.role,'blue-pill')));const roles=n('div','p12-role-list');['ADMIN','CAIXA','GARCOM','COZINHA','ENTREGADOR'].forEach(r=>roles.append(btn(r,'role',r)));const lessons=n('div','p12-lessons');lessons.id='p12Lessons';profile.append(roles,lessons);grid.append(profile);
 const guided=n('article','panel');guided.append(head('Modo Guiado','Tutorial diretamente sobre a interface',pill(state.level,'green')));const box=n('div','p12-guide');box.id='p12Guide';guided.append(box,btn('Iniciar guia: cadastrar produto','guide-next','product'));grid.append(guided);root.append(grid);
 const knowledge=n('article','panel');knowledge.append(head('Central de Ajuda + Pergunte ao NEXO','Contexto controlado por perfil, módulo, tela e versão',pill('Conteúdo versionado','purple')));const cards=n('div','p12-cards');[['Como fechar o caixa?','Caixa'],['O que é estoque mínimo?','Estoque'],['Como enviar pedido pelo garçom?','Pedidos'],['Impressora não responde','Drivers'],['Como configurar o Fiscal?','Fiscal']].forEach(([q,m])=>{const c=n('div','p12-card');c.append(pill(m,'neutral'),n('strong','',q),btn('Como fazer?','help',q));cards.append(c)});knowledge.append(cards);root.append(knowledge);
 const result=n('div','p12-result');result.id='p12Result';result.setAttribute('aria-live','polite');result.textContent='Nenhum guia iniciado.';root.append(result);page.append(root);renderLessons();renderGuide();
}
function renderLessons(){const root=d.getElementById('p12Lessons');if(!root)return;root.replaceChildren();(tracks[state.role]||[]).forEach((x,i)=>{const row=n('div','p12-lesson');row.append(pill(i<2?'CONCLUÍDO':'PENDENTE',i<2?'ok':'neutral'),n('span','',x));root.append(row)})}
function renderGuide(){const root=d.getElementById('p12Guide');if(!root)return;root.replaceChildren();const steps=['Clique em Produtos.','Clique em Novo Produto.','Informe o nome.','Informe o preço de venda.','Revise e clique em Salvar.'];const idx=Math.min(state.guideStep,steps.length-1);root.append(pill(`PASSO ${idx+1} DE ${steps.length}`,'blue-pill'),n('strong','',steps[idx]),n('small','',state.guideStep>=steps.length?'Tarefa concluída no cenário LAB.':'A validação real será feita pelo Core privado.'))}
function load(){ensureCss();buildLearning()}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',load,{once:true});else load();
d.addEventListener('click',e=>{const t=e.target.closest('[data-p12-action]');if(!t)return;const a=t.dataset.p12Action;if(a==='role'){state.role=t.dataset.value;renderLessons();announce(`Treinamento ajustado para o perfil ${state.role}.`)}else if(a==='guide-next'){state.guideStep=Math.min(state.guideStep+1,5);renderGuide();const r=d.getElementById('p12Result');if(r)r.textContent=state.guideStep>=5?'✅ Tarefa demonstrativa concluída.':'Guia em andamento; nenhuma alteração comercial foi gravada.'}else if(a==='help'){const r=d.getElementById('p12Result');if(r)r.textContent=`Ajuda contextual LAB: ${t.dataset.value}. A resposta oficial será filtrada pela versão instalada e pelo perfil do usuário.`;announce('Ajuda contextual aberta.')}});
})();
